apiVersion: v1
kind: ConfigMap
metadata:
  name: "lightspeed-vend-pos---complete-ecosystem-edition"-config
  namespace: "lightspeed-vend-pos---complete-ecosystem-edition"
data:
  db_host: "mysql-"lightspeed-vend-pos---complete-ecosystem-edition""
  redis_host: "redis-"lightspeed-vend-pos---complete-ecosystem-edition""
  app_env: "production"
  app_debug: "false"