apiVersion: v1
kind: ConfigMap
metadata:
  name: lightspeed-vend-pos---advanced-edition-config
  namespace: lightspeed-vend-pos---advanced-edition
data:
  db_host: "mysql-lightspeed-vend-pos---advanced-edition"
  redis_host: "redis-lightspeed-vend-pos---advanced-edition"
  app_env: "production"
  app_debug: "false"