apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lightspeed-vend-pos---advanced-edition-ingress
  namespace: lightspeed-vend-pos---advanced-edition
spec:
  ingressClassName: nginx
  rules:
  - host: lightspeed-vend-pos---advanced-edition.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lightspeed-vend-pos---advanced-edition-service
            port:
              number: 80
  tls:
  - hosts:
    - lightspeed-vend-pos---advanced-edition.example.com
    secretName: lightspeed-vend-pos---advanced-edition-tls