apiVersion: v1
kind: Service
metadata:
  name: lightspeed-vend-pos---advanced-edition-service
  namespace: lightspeed-vend-pos---advanced-edition
spec:
  type: LoadBalancer
  selector:
    app: lightspeed-vend-pos---advanced-edition
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000